title: MB
url: "https://mbraccini.github.io"
baseurl: "/michele.braccini/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/mbraccini/"
footer_text: "Michele Braccini - GitHub"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/michele.braccini/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
